[build]
  # Base directory for Netlify to run the build command
  base = ""
  
  # Build command to run our custom build script
  command = "./netlify-build.sh"
  
  # Directory to deploy (where your static files are after build)
  publish = "frontend/src/main/resources"

[build.environment]
  # Java/SBT version configuration
  JAVA_VERSION = "11"

# Headers for proper content types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Redirects for single-page app if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}
  
# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200