[build]
  command = "./build.sh"
  publish = "frontend/src/main/resources"

[build.environment]
  SBT_VERSION = "1.9.0"
  SCALA_VERSION = "3.3.6"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 