//addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.2")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.29")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler-sjs06" % "0.17.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.2")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalajsbundler" % "0.20.0")
addSbtPlugin("ch.epfl.scala" % "sbt-web-scalajs-bundler" % "0.21.1")
addSbtPlugin("io.github.cquiroz" % "sbt-tzdb" % "4.2.0")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0-RC2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.0")
resolvers += Resolver.bintrayRepo("oyvindberg", "converter")
resolvers += Resolver.bintrayRepo("oyvindberg", "converter-snapshots")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta42")